apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ab9nlcxht-python 
  janus-idp.io/tekton: ab9nlcxht-python
  backstage.io/kubernetes-id: ab9nlcxht-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ab9nlcxht-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  